### ISSUE TITLE
Linux aarch64 not built

### ISSUE THREAD

**Issue by GiovanniBussi** [conda-forge/xdrfile-feedstock#9]
For some reason, the `linux-aarch64` file was not uploaded at Anaconda for the last build (build number 1). On the other hand, this file was uploaded for the previous build (build number 0). See files [here](https://anaconda.org/conda-forge/xdrfile/files). The only differences that I applied from build 0 to build 1 are:
- adding host dependence on `libnsl` so as to fix #6 
- rerendering

Notice that I realized this problem by analyzing the failure of [this PR](https://github.com/conda-forge/py-plumed-feedstock/pull/20) doing a Python 3.10 migration. In particular on the `linux-aarch64` architecture, conda only finds build 0, which is not working correctly.

@conda-forge/core could you please help on this?

Thanks!

Giovanni

- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by dopplershift** [comment]
I think this was hit by [Drone silently dropping builds](https://github.com/conda-forge/status/issues/122). We have moved to most of our builds for aarch64/ppc64le being built with cross-compilation/emulation. If you rerender the feedstock, that should set things up and merging it should result in the package being built.

**Comment by GiovanniBussi** [comment]
It worked, thanks @dopplershift !
